[package]
resolver = "2"
name = "{{project-name}}"
version = "0.1.11"
description = "Keyboard firmware written in Rust"
homepage = ""
repository = ""
readme = ""
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
rmk = { version = "0.1.11", features = [
    "{{ chip }}_ble",
    "eeprom",
    "col2row",
] }
esp32-nimble = { version = "0.6.0", default-features = false, features = [
    "no_std",
] }
defmt = "0.3"
embassy-time = { version = "0.3.0", features = ["defmt", "generic-queue-8"] }
embassy-executor = { version = "0.5.0", features = [
    "arch-riscv32",
    "nightly",
    "executor-thread",
    "defmt",
] }
esp-println = { version = "0.9", features = [
    "{{ chip }}",
    "defmt-espflash"
]}
esp-idf-svc = { version = "0.48", default-features = false, features = [
    "alloc_handler",
    "embassy-sync",
    "binstart",
    "critical-section",
    "embassy-time-driver",
    "panic_handler",
] }
static_cell = "2.0"
riscv-rt = "0.12"

[build-dependencies]
xz2 = "0.1.7"
json = "0.12"
const-gen = "1.6"
embuild = "0.31.3"

[profile.dev]
codegen-units = 1      # better optimizations
debug = true
opt-level = 3          # esp-wifi should be built with opt-level 2 or 3
overflow-checks = true
lto = false
panic = 'unwind'

[profile.release]
codegen-units = 1       # better optimizations
debug = true            # no overhead for bare-metal
opt-level = 3           # esp-wifi should be built with opt-level 2 or 3
overflow-checks = false
lto = "fat"
