[hooks]
pre = ["pre-script.rhai"]
post = ["post-script.rhai"]

[template]
ignore = ["README.md"]

[placeholders.microcontroller_family]
type = "string"
prompt = "Choose your microcontroller family"
choices = ["stm32", "rp2040", "nrf", "esp"]
default = "stm32"

[conditional.'microcontroller_family == "stm32"'.placeholders.target]
type = "string"
prompt = "Choose your microcontroller's target"
choices = [
    "thumbv6m-none-eabi",
    "thumbv7em-none-eabi",
    "thumbv7em-none-eabihf",
    "thumbv7m-none-eabi",
    "thumbv8m.main-none-eabihf",
]
default = "thumbv7em-none-eabihf"

[conditional.'microcontroller_family == "nrf"'.placeholders.connection]
type = "string"
prompt = "Use BLE(wireless) or USB?"
choices = ["BLE", "USB"]
default = "BLE"

[conditional.'microcontroller_family == "esp"'.placeholders.connection]
type = "string"
prompt = "Use BLE(wireless) or USB(not supported now)?"
choices = ["BLE"]
default = "BLE"

[conditional.'microcontroller_family == "esp"'.placeholders.chip]
type = "string"
prompt = "Choose your esp MCU model"
choices = ["esp32c3", "esp32s3"]
default = "esp32c3"

# Chip models
[conditional.'microcontroller_family == "nrf" && connection == "USB"'.placeholders.chip]
type = "string"
prompt = "Choose your nrf MCU model"
choices = ["nrf52840", "nrf52833", "nrf52820"]
default = "nrf52840"

[conditional.'microcontroller_family == "nrf" && connection == "BLE"'.placeholders.chip]
type = "string"
prompt = "Choose your nrf MCU model (Embassy feature name)"
choices = ["nrf52840", "nrf52832"]
default = "nrf52840"

[conditional.'microcontroller_family == "stm32"'.placeholders.chip]
type = "string"
prompt = "Enter your MCU model(Embassy feature name)"

# Ignores
[conditional.'microcontroller_family == "stm32"']
ignore = [
    'Cargo_rp.toml',
    'Cargo_esp.toml',
    'Cargo_nrf.toml',
    'Cargo_nrf_ble.toml',
    'sdkconfig.defaults',
    's140_nrf52_7.3.0_softdevice.hex',
    'gen_test_projects.sh',
    '.github/test.yml',
    '.github/test_esp.yml',
]

[conditional.'microcontroller_family == "nrf" && connection == "USB"']
ignore = [
    'Cargo_stm32.toml',
    'Cargo_rp.toml',
    'Cargo_nrf_ble.toml',
    'Cargo_esp.toml',
    's140_nrf52_7.3.0_softdevice.hex',
    'sdkconfig.defaults',
    'gen_test_projects.sh',
    '.github/test.yml',
    '.github/test_esp.yml',
]

[conditional.'microcontroller_family == "rp2040"']
ignore = [
    'Cargo_stm32.toml',
    'Cargo_nrf.toml',
    'Cargo_nrf_ble.toml',
    'Cargo_esp.toml',
    's140_nrf52_7.3.0_softdevice.hex',
    'sdkconfig.defaults',
    'gen_test_projects.sh',
    '.github/test.yml',
    '.github/test_esp.yml',
]

[conditional.'microcontroller_family == "esp"']
ignore = [
    'Cargo_stm32.toml',
    'Cargo_rp.toml',
    'Cargo_nrf.toml',
    'Cargo_nrf_ble.toml',
    's140_nrf52_7.3.0_softdevice.hex',
    'memory.x',
    'gen_test_projects.sh',
    '.github/test.yml',
    '.github/test_esp.yml',
]

[conditional.'microcontroller_family == "nrf" && connection == "BLE"']
ignore = [
    'Cargo_stm32.toml',
    'Cargo_rp.toml',
    'Cargo_nrf.toml',
    'Cargo_esp.toml',
    'sdkconfig.defaults',
    '.github/test.yml',
    '.github/test_esp.yml',
    'gen_test_projects.sh',
]
