[hooks]
pre = ["pre-script.rhai"]
post = ["post-script.rhai"]

[template]
ignore = ["README.md"]

[placeholders.microcontroller_family]
type = "string"
prompt = "Choose your microcontroller family"
choices = ["stm32", "rp2040", "nrf"]
default = "stm32"

[conditional.'microcontroller_family == "stm32"'.placeholders.target]
type = "string"
prompt = "Choose your microcontroller's target"
choices = [
    "thumbv6m-none-eabi",
    "thumbv7em-none-eabi",
    "thumbv7em-none-eabihf",
    "thumbv7m-none-eabi",
    "thumbv8m.main-none-eabihf",
]
default = "thumbv7em-none-eabihf"

[conditional.'microcontroller_family == "nrf"'.placeholders.connection]
type = "string"
prompt = "Use BLE(wireless) or USB?"
choices = ["BLE", "USB"]
default = "BLE"

# Chip models
[conditional.'microcontroller_family == "nrf" && connection == "USB"'.placeholders.chip]
type = "string"
prompt = "Choose your nrf MCU model"
choices = [
    "nrf52840",
    "nrf52833",
    "nrf52820",
]
default = "nrf52840"

[conditional.'microcontroller_family == "nrf" && connection == "BLE"'.placeholders.chip]
type = "string"
prompt = "Choose your nrf MCU model (Embassy feature name)"
choices = ["nrf52840", "nrf52832"]
default = "nrf52840"

[conditional.'microcontroller_family == "stm32"'.placeholders.chip]
type = "string"
prompt = "Enter your MCU model(Embassy feature name)"

# Ignores
[conditional.'microcontroller_family == "stm32"']
ignore = [
    'src/main_rp.rs',
    'src/main_nrf.rs',
    'src/main_nrf_ble.rs',
    'src/main_nrf_ble_only.rs',
    'Cargo_rp.toml',
    'Cargo_nrf.toml',
    'Cargo_nrf_ble.toml',
    's140_nrf52_7.3.0_softdevice.hex',
]

[conditional.'microcontroller_family == "rp2040"']
ignore = [
    'src/main_stm32.rs',
    'src/main_nrf.rs',
    'src/main_nrf_ble.rs',
    'src/main_nrf_ble_only.rs',
    'Cargo_stm32.toml',
    'Cargo_nrf.toml',
    'Cargo_nrf_ble.toml',
    's140_nrf52_7.3.0_softdevice.hex',
]

[conditional.'microcontroller_family == "nrf" && connection == "USB"']
ignore = [
    'src/main_stm32.rs',
    'src/main_rp.rs',
    'src/main_nrf_ble.rs',
    'src/main_nrf_ble_only.rs',
    'Cargo_stm32.toml',
    'Cargo_rp.toml',
    'Cargo_nrf_ble.toml',
    's140_nrf52_7.3.0_softdevice.hex',
]

[conditional.'microcontroller_family == "nrf" && connection == "BLE" && chip == "nrf52832"']
ignore = [
    'src/main_stm32.rs',
    'src/main_rp.rs',
    'src/main_nrf.rs',
    'src/main_nrf_ble.rs',
    'Cargo_stm32.toml',
    'Cargo_rp.toml',
    'Cargo_nrf.toml',
]

[conditional.'microcontroller_family == "nrf" && connection == "BLE" && chip != "nrf52832" ']
ignore = [
    'src/main_stm32.rs',
    'src/main_rp.rs',
    'src/main_nrf.rs',
    'src/main_nrf_ble_only.rs',
    'Cargo_stm32.toml',
    'Cargo_rp.toml',
    'Cargo_nrf.toml',
]
