[hooks]
pre = ["pre-script.rhai"]
post = ["post-script.rhai"]

[template]
ignore = [ "README.md" ]

[placeholders.microcontroller_family]
type = "string"
prompt = "Choose your microcontroller family"
# TODO: add nrf
choices = ["stm32", "rp"]
default = "stm32"

[conditional.'microcontroller_family != "rp"'.placeholders.target]
type = "string"
prompt = "Choose your microcontroller's target"
choices = [
    "thumbv6m-none-eabi",
    "thumbv7em-none-eabi",
    "thumbv7em-none-eabihf",
    "thumbv7m-none-eabi",
    "thumbv8m.main-none-eabihf",
    "riscv32imac-unknown-none-elf",
]
default = "thumbv7em-none-eabihf"

[conditional.'microcontroller_family == "stm32"']
ignore = ['src/main_rp.rs', 'src/main_nrf.rs']
[conditional.'microcontroller_family == "rp"']
ignore = ['src/main_stm32.rs', 'src/main_nrf.rs']

[conditional.'microcontroller_family == "stm32" || microcontroller_family == "nrf"'.placeholders.chip]
type = "string"
prompt = "Enter your MCU model(Embassy feature name)"
