[toolchain]
{% if chip == "esp32c3" -%}
channel = "nightly"
components = ["rust-src", "rustfmt", "llvm-tools"]
{% elsif chip == "esp32s3" -%}
channel = "esp"
{% else -%}
channel = "stable"
components = ["rust-src", "rustfmt", "llvm-tools"]
{% endif -%}
