{% if microcontroller_family == "esp" %}
[target.riscv32imc-esp-espidf]
linker = "ldproxy"
rustflags = [ "--cfg",  "espidf_time64"] # Extending time_t for ESP IDF 5: https://github.com/esp-rs/rust/issues/110
{% else %}
[target.'cfg(all(target_arch = "arm", target_os = "none"))']
{% endif %}
{% if microcontroller_family == "rp2040" %}
runner = "probe-rs run --chip rp2040"
rustflags = []
{% elsif microcontroller_family == "esp" %}
runner = "espflash flash --monitor --log-format defmt"
{% else %}
# TODO: use `probe-rs chip list` to get your chip name 
runner = "probe-rs run --chip {{ chip }}"
rustflags = []
{% endif %}

[build]
# TODO: Pick a correct compilation target for your microcontroller
target = "{{ target }}"

[env]
# TODO: set DEFMT_LOG to "error" to reduce the binary size
DEFMT_LOG = "info"
{% if microcontroller_family == "esp" %}
MCU="esp32c3"
# Note: this variable is not used by the pio builder (`cargo build --features pio`)
ESP_IDF_VERSION = "v5.1.3"
ESP_IDF_PATH_ISSUES="warn"
# For macOS
CRATE_CC_NO_DEFAULTS="1"

[unstable]
build-std = ["core", "alloc", "panic_abort"]
{% endif %}