[tasks.install-llvm-tools]
install_crate = { rustup_component_name = "llvm-tools" }

[tasks.objcopy]
install_crate = { crate_name = "cargo-binutils", binary = "cargo", test_arg = [
    "objcopy",
    "--help",
] }
command = "cargo"
args = ["+esp", "objcopy", "--release", "--", "-O", "ihex", "{{ project_name }}.hex"]
dependencies = ["install-llvm-tools"]

[tasks.uf2]
command = "python"
args = [
    "scripts/uf2conv.py",
    "{{ project_name }}.hex",
    "-c",
    "-f",
    "esp32c6",                  # Use your chip family ID in the uf2conv.py file as -f argument
    "-o",
    "{{ project_name }}.uf2",
]
dependencies = ["objcopy"]
