name: Test rmk-template

on:
  push:
    branches: [ "master", "feat/rework" ]
  pull_request:
    branches: [ "master", "feat/rework" ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build_rp2040:
    runs-on: ubuntu-latest
    steps:
    - uses: cargo-bins/cargo-binstall@main
    - name: Install rmk-cli and cargo-make
      run: cargo binstall cargo-make rmk-cli -y
    - name: Install target
      working-directory: ..
      run: rustup default stable && rustup target add thumbv6m-none-eabi
    - name: Create project
      run: rmkit init --project-name rp2040_test --chip rp2040 --split false --local-path rp2040
    - name: Build rp2040
      working-directory: ./rp2040_test
      run: cargo make uf2 --release

      # run: rustup default stable && rustup target add thumbv7em-none-eabihf thumbv6m-none-eabi thumbv7em-none-eabi thumbv6m-none-eabi
    # - name: Build nrf52832_ble
    #   working-directory: ../nrf52832_ble
    #   run: cargo build --release
    # - name: Build nrf52840_ble
    #   working-directory: ../nrf52840_ble
    #   run: cargo build --release
    # - name: Build nrf_usb
    #   working-directory: ../nrf_usb
    #   run: cargo build --release
    # - name: Build stm32
    #   working-directory: ../stm32h7
    #   run: cargo build --release
    # - name: Build rp2040 split
    #   working-directory: ../rp_split
    #   run: cargo build --release --bin central && cargo build --release --bin peripheral
    # - name: Build nrf52840 split
    #   working-directory: ../nrf52840_ble_split
    #   run: cargo build --release --bin central && cargo build --release --bin peripheral

